services:
  web:
    build: ./web
    container_name: web_service
    ports:
      - "8888:8080"
    depends_on:
      - db
      - cache
    environment:
      - POSTGRES_DB=meubanco
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=senha
    networks:
      - minha_rede

  db:
    image: postgres:15
    container_name: db_service
    environment:
      - POSTGRES_DB=meubanco
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=senha
    volumes:
      - dados_postgres:/var/lib/postgresql/data
    networks:
      - minha_rede

  cache:
    image: redis:7
    container_name: cache_service
    networks:
      - minha_rede

networks:
  minha_rede:

volumes:
  dados_postgres: